#! /bin/bash

ACTION="custompart-parole_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding Zoom to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/parole/usr/local/bin/parole Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/parole
echo '#include <abstractions/ubuntu-browsers.d/parole>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
