#! /bin/bash

ACTION="custompart-signal_apparmor"

# Add apparmor profile to trust Signal in Firefox
logger -it "$ACTION" "Adding Signal to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/signal/opt/Signal/signal-desktop Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/signal
echo '#include <abstractions/ubuntu-browsers.d/signal>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
