#! /bin/bash

ACTION="custompart-jitsi_apparmor"

# Add apparmor profile to trust Jitsi in Firefox
logger -it "$ACTION" "Adding jitsi to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/jitsi/usr/bin/jitsi Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/jitsi
echo '#include <abstractions/ubuntu-browsers.d/jitsi>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
