#! /bin/bash

ACTION="custompart-vmrc_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding vmrc to firefox apparmor profile"
#echo "$( get custom_partition.mountpoint )/vmrc/usr/bin/vmrc Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/vmrc
echo "/usr/lib/vmware/bin/appLoader Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/vmrc
echo '#include <abstractions/ubuntu-browsers.d/vmrc>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
