#! /bin/bash

ACTION="custompart-otpclient_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding Zoom to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/otpclient/usr/bin/otpclient Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/otpclient
echo '#include <abstractions/ubuntu-browsers.d/otpclient>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
