#! /bin/bash

ACTION="custompart-icedtea_apparmor"

# Add apparmor profile to trust Remote Desktop Manager in Firefox
logger -it "$ACTION" "Adding IcedTea-Web to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/icedtea/services/zulu_jre8/jre/bin/javaws Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/icedtea
echo '#include <abstractions/ubuntu-browsers.d/icedtea>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
