#! /bin/bash

ACTION="custompart-keepass_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding keepass to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/keepass/usr/bin/keepass2 Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/keepass
echo '#include <abstractions/ubuntu-browsers.d/keepass>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
