#! /bin/bash

ACTION="custompart-pexip_apparmor"

# Add apparmor profile to trust Pexip in Firefox
logger -it "$ACTION" "Adding Microsoft Teams to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/custom/pexip/usr/lib/pexip-infinity-connect_linux-x64/pexip-infinity-connect Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/pexip
echo '#include <abstractions/ubuntu-browsers.d/pexip>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
