#! /bin/bash

ACTION="custompart-epson_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding Epson to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/epson/usr/lib/x86_64-linux-gnu/utsushi/utsushi-main Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/epson
echo '#include <abstractions/ubuntu-browsers.d/epson>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
