#! /bin/bash

ACTION="custompart-parallels_apparmor"

# Add apparmor profile to trust in Firefox
logger -it "$ACTION" "Adding parallels to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/parallels/opt/2X/Client/bin/2XClient Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/parallels
echo '#include <abstractions/ubuntu-browsers.d/parallels>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
