#! /bin/bash

ACTION="custompart-waykclient_apparmor"

# Add apparmor profile to trust Wayk Bastion Client in Firefox
logger -it "$ACTION" "Adding Wayk Bastion Client to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/waykclient/usr/bin/wayk-client Uxr," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/waykclient
echo '#include <abstractions/ubuntu-browsers.d/waykclient>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
